version: '3'

services:
  api:
    working_dir: /app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - PORT=3000
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_LICENSE_KEY=key
      - NEW_RELIC_APP_NAME=node-api
    network_mode: bridge
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
